### ISSUE TITLE
exclude nodemodules folder from project

### ISSUE THREAD

**Issue by JanEggers** [tehmantra/saunter#105]
I just pulled 0.5 src and visual studio (resharper) is super slow because of the node modules.

it would be nice if you could exclude the nodemodules from the csproj to speed up dev experience

**Comment by tehmantra** [comment]
Ahh interesting, I use Rider which seems to only include those 2 files explicitly included in the csproj. 
I will see what I can do for Visual Studio users 🧐

**Comment by JanEggers** [comment]
thx
