### ISSUE TITLE
add support for asyncapi 2.1

### ISSUE THREAD

**Issue by JanEggers** [tehmantra/saunter#107]
https://www.asyncapi.com/blog/release-notes-2.1.0

i dont know if you actually need to change something in the schema or its just a matter of changing the asyncapi property of the document.

I basicly dont want to get bothered by the asyncapi ui that is telling me every time i open it that i could update

**Comment by tehmantra** [comment]
I will investigate and fix. Thanks

**Comment by tehmantra** [comment]
Released in https://www.nuget.org/packages/Saunter/0.7.0
