### ISSUE TITLE
Is it possible to change Async API version?

### ISSUE THREAD

**Issue by jorgeromeral** [tehmantra/saunter#121]
Hi,

I wonder if it exists any possibility to generate the async API in a version other than the 2.1.0 (latest one)

Thanks for support!

**Comment by tehmantra** [comment]
No, not currently.
I'm curious what the use-case for this is? Which version would you want to generate and why?

**Comment by jorgeromeral** [comment]
In my case, I'm using microcks for API testing and management, and the documentation generator don't support that version. For this reason, I would like to generate the Async API in the 2.0.0 version. However, in 2 weeks, it seems that they are going to release a new version of Microcks, fixing 2.1.0 support.

**Comment by tehmantra** [comment]
Thanks. Supporting multiple versions will not likely be something I'll be supporting, as it's much easier to just target the latest version.
Older versions of the spec are produced by older versions of the library so they could be used if temporarily needed.
https://github.com/tehmantra/saunter/blob/main/CHANGELOG.md
