### ISSUE TITLE
Async API 2.2.0

### ISSUE THREAD

**Issue by daniel5053** [tehmantra/saunter#122]
Hi,

Following the AsyncAPI 2.2.0 specs,
They added new property to the channel entry called "servers" - which is the connection between channel and its server/servers

Will you support it soon?

**Comment by tehmantra** [comment]
Just had a look at the [release notes for 2.2.0](https://www.asyncapi.com/blog/release-notes-2.2.0), sounds like this will be pretty easy to implement.

Plan will be to add it as another property in the `ChannelAttribute` so usage would be like `[Channel("foo.bar", Servers = new[] { "my-server" })]`.
And of course it could be populated by any `IChannelItemFilter` too.

Will look to get this out this week.

**Comment by tehmantra** [comment]
Hi there, this will be available in v0.9.0 

![image](https://user-images.githubusercontent.com/3260812/137607313-9610cee8-5a6e-4f85-bef9-a69c716b86e6.png)

![image](https://user-images.githubusercontent.com/3260812/137607316-db639aff-2c3b-4b19-bf57-9a938cf7e3a0.png)
