### ISSUE TITLE
UI of sample project does not load

### ISSUE THREAD

**Issue by ITDancer13** [tehmantra/saunter#129]
I realized that sample project "StreetlightsAPI" seems to be broken.

Repro Steps:
- Download main branch and start StreetlightsAPI
- Try to access /asyncapi/ui

Result: 
Empty page and dev console shows this error.

![image](https://user-images.githubusercontent.com/11077626/145804806-62c6bda4-8ac5-477b-876a-7e0523ac1944.png)

Does anyone have the same issue and knows how to fix it?

**Comment by tehmantra** [comment]
Heya, you need to run `non install` from the `src/Saunter.UI` directory.

This is not done automatically by MSBuild so that it's possible to build the library without needing Nodejs/NPM.

**Comment by tehmantra** [comment]
Instructions have been added to the example project readme
https://github.com/tehmantra/saunter/tree/main/examples/StreetlightsAPI#running
