### ISSUE TITLE
Subscriptions?

### ISSUE THREAD

**Issue by jstafford5380** [tehmantra/saunter#130]
It seems subscriptions are completely left out. Is that just state of the project or are there examples somewhere?

**Comment by tehmantra** [comment]
Subscriptions are supported using the [SubscribeOperation] attribute.
Example here: https://github.com/tehmantra/saunter/blob/d3d09aaa118fe6a0ec730a4ac08bd3f9a74f01e9/examples/StreetlightsAPI/Messaging.cs#L25
