### ISSUE TITLE
NJsonSchema uses unsupported Json Schema.

### ISSUE THREAD

**Issue by VisualBean** [tehmantra/saunter#138]
NJsonSchema, leans against draft 04, which for some properties, is not supported by AsyncAPI.

AsyncAPI specifically leans against draft 07, which refers to the validation rfc 01 (https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01).

For instance, `AdditionalProperties`, is a map, not a boolean, in this draft.

**Comment by tehmantra** [comment]
Should be fixed by https://github.com/tehmantra/saunter/pull/143

**Comment by tehmantra** [comment]
Fixed in v0.10.0 https://www.nuget.org/packages/Saunter/0.10.0
