### ISSUE TITLE
Channel Operation should support multiple messages

### ISSUE THREAD

**Issue by joaopi** [tehmantra/saunter#14]
Currently, Channel is an attribute for a method and the Operation must be an attribute in the same method and only a message type can be provided.

If I repeat the Channel with the same name, on another method, it generates an error indicating the Channel is already added as a key in a Dictionary.

**So it's only possible to describe a single Message to one Channel within one Operation.**

For example, in my case, I have a Kafka topic that aggregates multiple messages.

In the specification, it describes that in an Operation, a Message Object can be declared as a set of possible message types (using oneOf): 
https://www.asyncapi.com/docs/specifications/2.0.0/#operationObject

A possible solution, that is more flexible, is to allow for Channels/Operations and Messages to be declared as independent attributes in multiple classes or methods. In this case, each Message Attribute would specify the Operation it belongs to, and when generating the document, it would update/add the message (stored as a collection) in the specified Operation object.

Thank you for your project and for your help!

**Comment by tehmantra** [comment]
Hi, apologies for the late reply, picking this up now :)

> A possible solution, that is more flexible, is to allow for Channels/Operations and Messages to be declared as independent attributes in multiple classes or methods. In this case, each Message Attribute would specify the Operation it belongs to, and when generating the document, it would update/add the message (stored as a collection) in the specified Operation object.

Can you give a code example of how (ideally) this would look for you (as the library user)?
I understand the issue, but I'm not sure exactly what the best user experience looks like.

Thanks

**Comment by joaopi** [comment]
Thank you for your reply!

I don't have a perfect solution but I think the best is decoupling channels from the message/method, but keeping the current solution for backward compatibility.

So for channels, I think it should be possible to declare them either on classes or methods. 
Using methods attributes would assume the current behavior of associating the Channel attribute with the Operation/Message.

When a Channel is declared as a class attribute, it would assume there is a channel and it might contain multiple messages under the same channel. 
By design of the asyncapi spec, a channel can only have one producer and one subscriber, the Operation must be declared also as a class attribute.

So it would require a new Message Attribute, associated with a method(?) (or should be other classes, the message classes?).
The Message would need to reference the OperationId as a key, and by doing so it would aggregate all messages related to the Operation/Channel.
 
Example:

    [AsyncApi]
    [Channel(TENANT_INSTANCES_TOPIC, Description = TENANT_TOPIC_DESCRIPTION)]
    // OperationId can assume the class name if not specified
    [SubscribeOperation([OperationId= "TenantMessageConsumer"], Summary = "Subscribe to domains events about tenants.")]
    public class TenantMessageConsumer :  ITenantMessageConsumer
    {
        internal const string TENANT_INSTANCES_TOPIC = "asw.tenant_service.tenants_history";

        [Message(typeof(TenantCreated), OperationId= "TenantMessageConsumer", Description = "...")]
        void SubscribeTenantCreatedEvent(Guid tenant_id, TenantCreated evnt) {}

        [Message(typeof(TenantUpdated), OperationId= "TenantMessageConsumer", Description = "...")]
        void SubscribeTenantUpdatedEvent(Guid tenant_id, TenantUpdated evnt) {}

        [Message(typeof(TenantRemoved), OperationId= "TenantMessageConsumer", Description = "...")]
        void SubscribeTenantRemovedEvent(Guid tenant_id, TenantRemoved  evnt)  {  }
   }

**Comment by tehmantra** [comment]
Ok, this looks good.
As I'm really only experienced with AMQP, I didn't understand the potential design differences with Kafka (and I'm sure there will be more differences with other implementations).

I will start working on this now 😀

**Comment by tehmantra** [comment]
Hello again, this is now in master.
See ClassAttributesTests for an example https://github.com/tehmantra/saunter/blob/master/test/Saunter.Tests/Generation/DocumentGeneratorTests/ClassAttributesTests.cs

This will be available on NuGet v0.1.0-alpha-46
https://www.nuget.org/packages/Saunter/0.1.0-alpha-46

**Comment by joaopi** [comment]
Thank you so much!
