### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by Anaster666** [tehmantra/saunter#148]
Good morning!

Is only a simple question about the Tags, is it implemented?

Now in my UI appears all the operations inside "untagged", how can I configure it?

I have this:
`[PublishOperation(typeof(StateUpdatedIntegrationEvent), Summary = "Inform the state change.")] `

Thanks!!

**Comment by ame0410** [comment]
`Operations.Tags` exists, but the `Tags` property isn't exposed in `OperationAttribute`.

**Comment by ame0410** [comment]
I just found this pull request #134 that attempts to solve the issue. @tehmantra will you be able to review it?

**Comment by tehmantra** [comment]
Looks like the PR has a couple of conflicts, I'll get them resolved and push out a new version.

**Comment by tehmantra** [comment]
Sorry for the delay - has been a busy couple of weeks - this is now published in v0.11.0
https://www.nuget.org/packages/Saunter/0.11.0

**Comment by Anaster666** [comment]
Hi!

First of all thanks for all the help. But I have a question about it. Am I using correctly this property?

[Channel("Candidature/StateUpdated")] // Creates a Channel
[Tags("Candidature")]
[PublishOperation(typeof(CandidatureStateUpdatedIntegrationEvent), new string[] { "Candidature"}, Summary = "Event summary" )]

Obviously I'm missing something because I have this error:

Error: There were errors validating the AsyncAPI document.
undefined./channels/Candidature~1StateUpdated/publish/tags/0/description should be string
undefined./channels/Candidature~1StateUpdated/publish/tags/0/externalDocs should be object

Thanks for all
