### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by m-wild** [tehmantra/saunter#155]
It's become clear I don't have time to give this project the love it deserves so I'm looking for options.

I'm open to accepting maintainers on the project and possibly moving the project to a new org (or to the asyncapi org if they will accept it).

Feel free to apply by responding to this issue.

**Comment by devlux** [comment]
hi @tehmantra, that's very sad to hear, thank you for the great work you've already done for this project! 

I could do some basic maintenance and help with some open refactoring. but I'll not be the one that is working days and nights on the project... ;-)

**Comment by VisualBean** [comment]
We have recently released asyncapi.net - which should take care of the basic building blocks, which we will maintain internally.

Perhaps this can make things a bit easier for saunter maintenance, so saunter is could be stripped down to simply the generator api's

**Comment by Krusty93** [comment]
Is there any news on this? I would like to hear what's the future of this library.

As @devlux says, I could do some basic maintenance as well

**Comment by cvietor** [comment]
+1 
i also can help with basic maintenance

**Comment by Filipedguy** [comment]
I work at a Brazilian Fintech, and we want to automate our Async documentation.
I think we can help maintain and improve this, if you want it

**Comment by derberg** [comment]
@tehmantra I can definitely help you out with requesting a move of this project under `asyncapi` org.

**Comment by tehmantra** [comment]
@derberg I think that's a good idea. 

The project will still need active maintainers, hopefully bringing it into the asyncapi org will enable that.

**Comment by derberg** [comment]
@tehmantra sorry, I missed you comment. I started using Volta for handling notifications and looks like it is not supporting repos that are outside my scope 😞 

My proposal is:
- open a discussion in AsyncAPI org, like https://github.com/orgs/asyncapi/discussions/643
- explain what project you want to donate
- specify if you stay as maintainer to onboard other maintainers

And we will help to make noise about it in he community, to join discussion, and figure out next steps. We can even mention request for support during our conferences https://conference.asyncapi.com/

wdyt?

**Comment by thompson-tomo** [comment]
@m-wild i am more than happy to contribute become a mantainer and I am actively looking at working through the issues I have logged as they will benefit not just me in my professional career but I am sure others will benefit too.
