### ISSUE TITLE
js is not served with .net 6 and named documents

### ISSUE THREAD

**Issue by JanEggers** [tehmantra/saunter#157]
![image](https://user-images.githubusercontent.com/6747376/213984777-f3924c75-64e7-47c8-8453-49aecc14dde5.png)

**Comment by devlux** [comment]
hi @JanEggers, can you please show how you configured your api (i.e. `Program.cs`)? did you call ` services.ConfigureNamedAsyncApi(...)` ?

**Comment by JanEggers** [comment]
I use ConfigureNamedAsyncApi and it was working as long as I used net4 (netstandard) we updated to net6 and saunter from 0.9 to 0.11. 

the html is served fine so there is no issue with casing or anything else. please have a look at #158. I already submitted a pr with a test that fixes the issue

**Comment by devlux** [comment]
I wanted to make sure I understood the issue correctly as the examples project within the solution was running fine but now with a dedicated solution I was able to reproduce the issue too... :-)

**Comment by JanEggers** [comment]
Hi I tried to repro the issue and found it in our code after all. We previously used 

```
  app.UseMiddleware<AsyncApiMiddleware>();
  app.UseMiddleware<AsyncApiUiMiddleware>();
```

instead of 

```
app.UseEndpoints(endpoints =>
{
    endpoints.MapAsyncApiDocuments();
    endpoints.MapAsyncApiUi();
});
```

that broke the js and css delivery
