### ISSUE TITLE
Handle Nullable types

### ISSUE THREAD

**Issue by tehmantra** [tehmantra/saunter#20]
See #16 

> Also, we should probably be handling Nullable differently to other generics...
> Json Schema allows for { "type": "null" }, see: https://json-schema.org/understanding-json-schema/reference/null.html
> Which means we could detect System.Nullable<T> and set the property as { "type": [ "T", "null" ] }

**Comment by neoaisac** [comment]
Thinking of looking into this for Hacktoberfest. Any pointers?

**Comment by tehmantra** [comment]
We generate a Document which contains Messages, each message has a Payload.

https://github.com/tehmantra/saunter/blob/279f51fce99847009b43badb522428638e3b6688/src/Saunter/Generation/DocumentGenerator.cs#L253

This `ISchema` is in JSON-Schema format.

When we set the `Schema.Type` property (which is currently a string) by reflecting types in the `SchemaGenerator`.

https://github.com/tehmantra/saunter/blob/279f51fce99847009b43badb522428638e3b6688/src/Saunter/Generation/SchemaGeneration/SchemaGenerator.cs#L31:L49

An example of a simple schema representing a non-nullable int:
```json
{
    "type": "integer"
}
```

An example representing a nullable int:
```json
{
    "type": ["integer", "null"]
}
```

We need to make `Schema.Type` render as either a string `"T"`, or if the type is nullable, an array containing `[ "T", "null" ]`.

We can optionally/additionally support the OpenAPI spec which defines an additional property `nullable: bool`
Example of nullable int in OpenAPI:
```
{
    "type": "integer",
    "nullable": true
}
```

**Comment by tehmantra** [comment]
This is implemented using a `[Flags] enum` in Newtonsoft.Json.Schema
https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/master/Src/Newtonsoft.Json.Schema/JSchemaType.cs

Same as NJsonSchema
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/JsonObjectType.cs

I suppose this is the easiest way to be able to set this as one or more value.

```csharp
// for non-nullable primitives
Type = JsonSchemaType.Integer;

// for nullable-primitives
Type = JsonSchemaType.Integer | JsonSchemaType.Null;
```

This also allows for setting the nullable type separate from the underlying type;
```
var type = JsonObjectType.Integer;

//... elsewhere
if (nullable) {
    type = type | JsonObjectType.Null;
}
```

**Comment by tehmantra** [comment]
Closing in favor of #60
