### ISSUE TITLE
Replace Newtonsoft.Json with System.Text.Json

### ISSUE THREAD

**Issue by tehmantra** [tehmantra/saunter#21]
As new projects use System.Text.Json by default, this should be our default to prevent adding extra dependencies for our users.

**Comment by SuNNjek** [comment]
Hey, I would like to look into this, could you assign me?

**Comment by SuNNjek** [comment]
@tehmantra Quick question: It seems like System.Text.Json doesn't have an equivalent to [JsonObjectAttribute](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonObjectAttribute.htm). This is used here: https://github.com/tehmantra/saunter/blob/94fb3f71a684da53f82fb287a11cde08c209d846/src/Saunter/Generation/DefaultSchemaIdFactory.cs#L52-L57

Now there would be two ways around this I can see:
- Use a different attribute (e.g. [System.ComponentModel.DataAnnotations.DisplayAttribute](https://docs.microsoft.com/de-de/dotnet/api/system.componentmodel.dataannotations.displayattribute?view=netcore-3.1))
- Define a custom attribute for this purpose

Which would you think is better?

**Comment by tehmantra** [comment]
It's probably best to just remove this as there is no equivalent in System.Text.Json.

The SchemaIdFactory can be set on the SaunterOptions (this is just the Default implementation) so it's easy for clients to provide their own implementation which inspects any attributes they like.
