### ISSUE TITLE
datetimeoffset creates recursive schema

### ISSUE THREAD

**Issue by JanEggers** [tehmantra/saunter#63]
"dateTimeOffset":{
            "properties":{
               "Now":{
                  "$ref":"#/components/schemas/dateTimeOffset"
               },
               "UtcNow":{
                  "$ref":"#/components/schemas/dateTimeOffset"
               },
               "DateTime":{
                  "type":"string",
                  "format":"date-time"
               },
               "UtcDateTime":{
                  "type":"string",
                  "format":"date-time"
               },
               "LocalDateTime":{
                  "type":"string",
                  "format":"date-time"
               },
               "Date":{
                  "type":"string",
                  "format":"date-time"
               },
               "Day":{
                  "type":"integer"
               },
               "DayOfWeek":{
                  "type":"string",
                  "enum":[
                     "Sunday",
                     "Monday",
                     "Tuesday",
                     "Wednesday",
                     "Thursday",
                     "Friday",
                     "Saturday"
                  ]
               },
               "DayOfYear":{
                  "type":"integer"
               },
               "Hour":{
                  "type":"integer"
               },
               "Millisecond":{
                  "type":"integer"
               },
               "Minute":{
                  "type":"integer"
               },
               "Month":{
                  "type":"integer"
               },
               "Offset":{
                  "type":"string",
                  "format":"time-span"
               },
               "Second":{
                  "type":"integer"
               },
               "Ticks":{
                  "type":"integer"
               },
               "UtcTicks":{
                  "type":"integer"
               },
               "TimeOfDay":{
                  "type":"string",
                  "format":"time-span"
               },
               "Year":{
                  "type":"integer"
               },
               "MinValue":{
                  "$ref":"#/components/schemas/dateTimeOffset"
               },
               "MaxValue":{
                  "$ref":"#/components/schemas/dateTimeOffset"
               },
               "UnixEpoch":{
                  "$ref":"#/components/schemas/dateTimeOffset"
               }
            }
         },

**Comment by tehmantra** [comment]
Would be fixed by #60 ...I will investigate

**Comment by christamlyn-bridge** [comment]
I think I am getting this same issue.  The schema generated is not valid according to the Async API playground.  New to AsyncAPI so not exactly sure why,

I have a simple class with a single DateTimeOffset property

`public class SomeEvent
    {
        public DateTimeOffset? DateTimeOffset { get; set; }
    }`

Which is generating a schema (below) which returns a 422 on POST.

In the SchemaGenerator class I note there is special handling for primitive types but nothing for DateTimeOffset.  Is it as simple as adding another primitive check for DateTimeOffsets?

`{
    "asyncapi": "2.0.0",
    "info": {
        "title": "Streetlights API",
        "version": "1.0.0",
        "description": "The Smartylighting Streetlights API allows you\nto remotely manage the city lights."
    },
    "servers": {},
    "defaultContentType": "application/json",
    "channels": {
        "some-channel": {
            "publish": {
                "operationId": "SomeMethod",
                "summary": "Some event.",
                "tags": [],
                "message": {
                    "payload": {
                        "$ref": "#/components/schemas/someEvent"
                    },
                    "name": "someEvent",
                    "tags": [],
                    "examples": [],
                    "traits": []
                },
                "traits": []
            },
            "parameters": {}
        }
    },
    "components": {
        "schemas": {
            "dateTimeOffset": {
                "properties": {
                    "now": {
                        "$ref": "#/components/schemas/dateTimeOffset"
                    },
                    "utcNow": {
                        "$ref": "#/components/schemas/dateTimeOffset"
                    },
                    "dateTime": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "utcDateTime": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "localDateTime": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "date": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "day": {
                        "type": "integer"
                    },
                    "dayOfWeek": {
                        "type": "integer",
                        "enum": [
                            0,
                            1,
                            2,
                            3,
                            4,
                            5,
                            6
                        ]
                    },
                    "dayOfYear": {
                        "type": "integer"
                    },
                    "hour": {
                        "type": "integer"
                    },
                    "millisecond": {
                        "type": "integer"
                    },
                    "minute": {
                        "type": "integer"
                    },
                    "month": {
                        "type": "integer"
                    },
                    "offset": {
                        "type": "string",
                        "format": "time-span"
                    },
                    "second": {
                        "type": "integer"
                    },
                    "ticks": {
                        "type": "integer"
                    },
                    "utcTicks": {
                        "type": "integer"
                    },
                    "timeOfDay": {
                        "type": "string",
                        "format": "time-span"
                    },
                    "year": {
                        "type": "integer"
                    },
                    "minValue": {
                        "$ref": "#/components/schemas/dateTimeOffset"
                    },
                    "maxValue": {
                        "$ref": "#/components/schemas/dateTimeOffset"
                    },
                    "unixEpoch": {
                        "$ref": "#/components/schemas/dateTimeOffset"
                    }
                }
            },
            "nullableOfDateTimeOffset": {
                "properties": {
                    "hasValue": {
                        "type": "boolean"
                    },
                    "value": {
                        "$ref": "#/components/schemas/dateTimeOffset"
                    }
                }
            },
            "someEvent": {
                "properties": {
                    "dateTimeOffset": {
                        "$ref": "#/components/schemas/nullableOfDateTimeOffset"
                    }
                }
            }
        },
        "messages": {},
        "securitySchemes": {},
        "parameters": {},
        "correlationIds": {},
        "serverBindings": {},
        "channelBindings": {},
        "operationBindings": {},
        "messageBindings": {},
        "operationTraits": {},
        "messageTraits": {}
    },
    "tags": []
}`

**Comment by tehmantra** [comment]
> In the SchemaGenerator class I note there is special handling for primitive types but nothing for DateTimeOffset.  Is it as simple as adding another primitive check for DateTimeOffsets?

Yes, that would be the quickest/simplest fix.

There is work in progress to replace the custom schema generation code with NJsonSchema, but this could be fixed in the meantime.
