### ISSUE TITLE
add ability to expose multiple async apis 

### ISSUE THREAD

**Issue by JanEggers** [tehmantra/saunter#64]
buhu we have a monolith :)

can you please expose any method to split / filter the api.

for my monster monolith it would be nice to split by first segment of channel name.

right now we write the aync api spec by hand and have:

AcountApi.*
ProductApi.*
.....

but as this is all hosted in one app i now only get a giant doc and i am not able to recreate what we had created manually

**Comment by tehmantra** [comment]
So ideally we would produce multiple documents from the same application? Each hosted at a different URL?
```
https://.../asyncapi/AccountApi-asyncapi.json
https://.../asyncapi/ProductApi-asyncapi.json
```

**Comment by JanEggers** [comment]
exactly

**Comment by JanEggers** [comment]
@tehmantra  i found this for swashbuckle maybe you could implement a similar approach

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#generate-multiple-swagger-documents

**Comment by tehmantra** [comment]
This is now available https://www.nuget.org/packages/Saunter/0.6.0
