### ISSUE TITLE
Herency

### ISSUE THREAD

**Issue by Anaster666** [tehmantra/saunter#66]
Is possible use classes that using herency? I use it to have a basic structure for every event and I add the necessary fields.

public class SyncDocumentIntegrationEvent : IntEvent
    {
        public int DocumentId { get; }
        public int UserId { get; }

        public SyncDocumentIntegrationEvent(int documentId, int userId) : base()
        {
            DocumentId = documentId;
            UserId = userId;
        }
    }

The document generated by asyncAPI is enormous and breaks the structure:

I'm doing something wrong?

Thanks for the help.

**Comment by tehmantra** [comment]
Would be fixed by #60

**Comment by tehmantra** [comment]
This is partially supported by using the `[Discriminator]` attribute
https://github.com/tehmantra/saunter/blob/291d2aa30fe054331106442bc8a4d9bc23bcdea3/test/Saunter.Tests/Generation/SchemaGeneration/SchemaGenerationTests.cs#L177


This issue will be closed in favor of #60
