### ISSUE TITLE
Add supported exchange types to the specification

### ISSUE THREAD

**Issue by gomete** [tehmantra/saunter#73]
In order to reduce typos, a list of exchange types could be provided as it is a short limited list: `The type of the exchange. Can be either topic, direct, fanout, default or headers.` (https://github.com/asyncapi/bindings/blob/master/amqp/README.md#channel).

The `is` property is an enum and this `exchange.type` seems to be the same case but:
- I don't know if it could grow or vary more often than `is`.
- It will be a breaking change.

So my proposal is to provide a static class with a list of constants just to have the supported options.

**Comment by tehmantra** [comment]
Closed by #74
