### ISSUE TITLE
Message could be a $ref in Operation.

### ISSUE THREAD

**Issue by fglaeser** [tehmantra/saunter#8]
Check this asyncapi documentation.

```yaml

channels:
  Envios/Traza/Admision:
    publish:
      operationId: Admision
      message:
        $ref: '#/components/messages/Admision'  

```
I think is no way to do that with the current classes. The Message should implement an Interface like Schema to have the possibility of add a Reference.

Best Regards,
Facundo

**Comment by tehmantra** [comment]
Closing in favor of #60
