### ISSUE TITLE
Allow setting description for attributes/parameters

### ISSUE THREAD

**Issue by claorden** [tehmantra/saunter#87]
Hi there!

An idea that I think it's not available right now (please correct me if it is). It would be very useful to be able to define the "description" field of the properties of a class via summary or metadata.

Example:
 ```
public sealed class MyClass
    {
        /// <summary>
        /// Att1 description.
        /// </summary>
        public double Att1 { get; set; }

        [Saunter.Attributes.ParameterDefinition(Description = "Att2 description.")]
        public double Att2 { get; set; }
    }
 ```
Resulting in:
 ```
"myClass":{"properties":{
        "Att1":{"type":"number", "description":"Att1 description."},
        "Att2":{"type":"number", "description":"Att2 description."}
}}
 ```

**Comment by tehmantra** [comment]
This is currently implemented https://github.com/tehmantra/saunter/blob/76818cccb9a5e512dd691ad0ce5b56566611f0bf/src/Saunter/Utils/Reflection.cs#L227

If it's not working, make sure that the the XML file is being generated at build time

```xml
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>
```
